version: "3.8"

services:
  app:
    build: .
    command: sh -c "poetry run python3 manage.py migrate &&
                    poetry run python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src:/code/src/
      - media:/code/src/media
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"

  db:
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    restart: always

  celery:
    build: .
    restart: always
    command: sh -c "poetry run celery -A config worker -l info"
    volumes:
      - ./src:/code/src/
      - media:/code/src/media
    depends_on:
      - db
      - redis
      - app
    env_file:
      - .env

volumes:
  postgres:
  media:
